# if io timeout: https://github.com/docker/for-mac/issues/6621
services:
  apm-mysql:
    image: mysql:9.0.1
    container_name: apm-mysql
    ports:
      - "23306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - ./volumes/mysql/logs:/var/log/mysql
    restart: always
  apm-redis:
    image: redis:7.4.0
    container_name: apm-redis
    ports:
      - "26379:6379"
    volumes:
      - ./volumes/redis/data:/data
      - ./volumes/redis/logs:/var/log/redis
    restart: always
